export const countryList = [
  { name: "Burundi", code: "BI" },
  { name: "Cameroon", code: "CM" },
  { name: "Chad", code: "TD" },
  { name: "Democratic Republic of Congo", code: "CD" },
  { name: "Congo", code: "CG" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Gabon", code: "GA" },
  { name: "Algeria", code: "DZ" },
  { name: "Morocco", code: "MA" },
  { name: "Tunisia", code: "TN" },
  { name: "Botswana", code: "BW" },
  { name: "Lesotho", code: "LS" },
  { name: "Namibia", code: "NA" },
  { name: "Swaziland", code: "SZ" },
  { name: "Madagascar", code: "MG" },
  { name: "Mauritius", code: "MU" },
  { name: "Malawi", code: "MW" },
  { name: "Seychelles", code: "SC" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
  { name: "Benin", code: "BJ" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Cape Verde", code: "CV" },
  { name: "Côte d’Ivoire", code: "CI" },
  { name: "Gambia", code: "GM" },
  { name: "Ghana", code: "GH" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Liberia", code: "LR" },
  { name: "Mali", code: "ML" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Senegal", code: "SN" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Togo", code: "TG" },
  { name: "Central African Republic", code: "CF" },
  { name: "Djibouti", code: "DJ" },
  { name: "São Tomé and Príncipe", code: "ST" },
];

export const allCountryList = [
  { name: "All", code: "All" },
  { name: "Burundi", code: "BI" },
  { name: "Cameroon", code: "CM" },
  { name: "Chad", code: "TD" },
  { name: "Democratic Republic of Congo", code: "CD" },
  { name: "Congo", code: "CG" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Gabon", code: "GA" },
  { name: "Algeria", code: "DZ" },
  { name: "Morocco", code: "MA" },
  { name: "Tunisia", code: "TN" },
  { name: "Botswana", code: "BW" },
  { name: "Lesotho", code: "LS" },
  { name: "Namibia", code: "NA" },
  { name: "Swaziland", code: "SZ" },
  { name: "Madagascar", code: "MG" },
  { name: "Mauritius", code: "MU" },
  { name: "Malawi", code: "MW" },
  { name: "Seychelles", code: "SC" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
  { name: "Benin", code: "BJ" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Cape Verde", code: "CV" },
  { name: "Côte d’Ivoire", code: "CI" },
  { name: "Gambia", code: "GM" },
  { name: "Ghana", code: "GH" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Liberia", code: "LR" },
  { name: "Mali", code: "ML" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Senegal", code: "SN" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Togo", code: "TG" },
  { name: "Central African Republic", code: "CF" },
  { name: "Djibouti", code: "DJ" },
  { name: "São Tomé and Príncipe", code: "ST" },
];

export const clickableCountries = [
  { name: "Kenya", code: "KE" },
  { name: "Uganda", code: "UG" },
  { name: "Tanzania", code: "TZ" },
  { name: "Rwanda", code: "RW" },
  { name: "Burundi", code: "BI" },
  { name: "Somalia", code: "SO" },
  { name: "Cameroon", code: "CM" },
  { name: "Chad", code: "TD" },
  { name: "Democratic Republic of Congo", code: "CD" },
  { name: "Congo", code: "CG" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Gabon", code: "GA" },
  { name: "Algeria", code: "DZ" },
  { name: "Morocco", code: "MA" },
  { name: "Tunisia", code: "TN" },
  { name: "Botswana", code: "BW" },
  { name: "Lesotho", code: "LS" },
  { name: "Namibia", code: "NA" },
  { name: "Swaziland", code: "SZ" },
  { name: "Madagascar", code: "MG" },
  { name: "Mauritius", code: "MU" },
  { name: "Malawi", code: "MW" },
  { name: "Seychelles", code: "SC" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
  { name: "Benin", code: "BJ" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Cape Verde", code: "CV" },
  { name: "Côte d’Ivoire (Ivory Coast)", code: "CI" },
  { name: "Gambia", code: "GM" },
  { name: "Ghana", code: "GH" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Liberia", code: "LR" },
  { name: "Mali", code: "ML" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Senegal", code: "SN" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Togo", code: "TG" },
  { name: "Central African Republic", code: "CF" },
  { name: "Djibouti", code: "DJ" },
  { name: "São Tomé and Príncipe", code: "ST" }
];

